### ISSUE TITLE
Nullable support in EF Core

### ISSUE THREAD

**Issue by kfrancis** [andrewlock/StronglyTypedId#22]
What's the best way to add nullable support here? You discuss it in previous posts, but it doesn't seem to be part of the library.

The property 'Claim.CaseId' could not be mapped, because it is of type 'Nullable<CaseId>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'

CaseId is defined:
```
[StronglyTypedId(jsonConverter: StronglyTypedIdJsonConverter.SystemTextJson | StronglyTypedIdJsonConverter.NewtonsoftJson, backingType: StronglyTypedIdBackingType.Guid)]
    public partial struct CaseId { }
```

And used:
```
public class Claim {
    public CaseId? CaseId { get; set; }
}
```

I have also:
```
public class CaseIdValueConverter : ValueConverter<CaseId, Guid>
    {
        public CaseIdValueConverter(ConverterMappingHints mappingHints = null)
            : base(
                id => id.Value,
                value => new CaseId(value),
                mappingHints
            )
        { }
    }
```
and `ReplaceService<IValueConverterSelector, StronglyTypedIdValueConverterSelector>()`

**Comment by patrolez** [comment]
@kfrancis: https://stackoverflow.com/questions/4491869/how-to-make-a-struct-nullable-by-definition

This suggests that no `struct` can be Nullable and proposed resolution seems to use `class` instead.

@andrewlock

**Comment by andrewlock** [comment]
> This suggests that no struct can be Nullable and a proposed solution is to use class instead

@patrolez You're getting confused between 2 concepts here. A class can be null naturally, and you're right that a struct _can't_ ever be null. However, you can make a Struct nullable using the `?` symbol, e.g. `CaseId` _can_ be null below.

```csharp
public class Claim {
    public CaseId? CaseId { get; set; }
}
```

As to the original question, this appears to be a problem with the value converters. I don't have a specific answer as it's not something I've ever tried to do. It's essentially an EF Core problem rather than this lib, but I don't have a solution off-hand, at this point

**Comment by vebbo2** [comment]
@kfrancis This is the way I'm using StronglyTypedId in EF Core, works fine with nullables

```
public static class ModelBuilderExtensions
    {
        public static void ApplyStronglyTypedIdConversion(this ModelBuilder modelBuilder)
        {
            foreach (var entityType in modelBuilder.Model.GetEntityTypes())
            {
                foreach (var property in entityType.GetProperties())
                {
                    if (property.ClrType.GetCustomAttribute<StronglyTypedIdAttribute>() != null)
                    {
                        var converterType = typeof(StronglyTypedIdValueConverter<>).MakeGenericType(property.ClrType);
                        var converter = (ValueConverter)Activator.CreateInstance(converterType);
                        property.SetValueConverter(converter);
                    }
                }
            }
        }
    }
```
and
```
public class StronglyTypedIdValueConverter<TId> : ValueConverter<TId, Guid>
    {
        public StronglyTypedIdValueConverter()
            : base(e => (Guid)e.GetType().GetProperty("Value").GetValue(e), e => (TId)Activator.CreateInstance(typeof(TId), e))
        {
        }
    }
```

PS. This code assumes you always use same backing type, in this case Guid

**Comment by dzmitry-lahoda** [comment]
@vebbo2 PR to handle all ids in EF?

**Comment by vebbo2** [comment]
@dzmitry-lahoda It would probably require separate package, core library definietely shouldn't depend on EF Core

**Comment by zyberzero** [comment]
@vebbo2 : Thanks for that! I borrowed your example. However, I can't get it to run - the problem is when looping over all properties in the entityType the property containing the strongly typed Id type is missing. For example, I have this entity:
```
    public class Option
    {
        public OptionId ID { get; set; }
        public string AnswerText { get; set; }
    }
```
Where OptionId is defined as:
```
    [StronglyTypedId]
    public partial struct OptionId { }
```
I get two properties for the entityType; AnswerType (string) and PollTempId (int32) - I guess that's due to the fact that the Option is owned by a Poll type (which also as ha StronglyTypedId as its key) - but I can't find any reference to the OptionId at all. Do you have any idea what I'm doing wrong?

**Comment by vebbo2** [comment]
@zyberzero I didn't handle owned types in my case, so no wonder it's not working :) But what comes to my mind right now is, while iterating over properties, just check if they are classes and then iterate over its properties for STI attribute as well. It's not a perfect solution but it might work for you

**Comment by zyberzero** [comment]
@vebbo2 : After thinking about it, it does not find any StronglyTypedIds, even though they are the root object. 

My DbContext has a DbSet<Poll>. It looks, somewhat minified as:

```
 public class Poll
    {
        public PollId Id { get; set; }
        public IList<Option> Options { get; set; }
    }
```

However, the Properties on that Entity are as follows:
```
entity.GetProperties()
Count = 1
    [0]: {Property: Poll.TempId (no field, int) Shadow Required AlternateKey AfterSave:Throw}
```

So it seems to me that EF does not want to see my StronglyTypedIds at all.  I think I'm doing something stupid but I can't really figure out what.

Is your code available so that I can take a look in how you did, and figure out what differs between us?

**Comment by vebbo2** [comment]
@zyberzero Sorry, it's private project, but I remember having similar issue. If your STIs are in different assembly, they may not visible because STI is marked with https://github.com/andrewlock/StronglyTypedId/blob/master/src/StronglyTypedId.Attributes/StronglyTypedIdAttribute.cs#L7 . To workaround this, add `CodeGeneration` to Conditional compilation symbols in your project

**Comment by andrewlock** [comment]
@zyberzero Just to jump in, but this doesn't look like a problem with StronglyTYpedIds to me, it looks like a problem with your EF Core mapping. For example, EF Core isn't recognising the `Options` property on your `Poll` entity at all - the fact that `Option.ID` is a strongly typed ID isn't a factor at that point I don't think.

That said, I don't do a lot of EF Core, so I could be wrong, but does it work if you switch `Option.Id` to being a simple `Guid`/`int`? That would help narrow things down

**Comment by andrewlock** [comment]
I've released [a beta version](https://www.nuget.org/packages/StronglyTypedId/1.0.0-beta01) of a major update to the library converts to using Source generators. There's quite a few breaking changes in the release, so please make sure to check the release notes for how to update, but I'd appreciate any feedback you have before I do a final release! The release adds direct support for ef core value converters.

I've also written a blog post announcing the update that goes into a bit more details: https://andrewlock.net/rebuilding-stongly-typed-id-as-a-source-generator-1-0-0-beta-release

Thanks! 🙂

**Comment by kfrancis** [comment]
Perfect, thanks!
