### ISSUE TITLE
Extensible Code Generation

### ISSUE THREAD

**Issue by megakid** [andrewlock/StronglyTypedId#4]
We use serialisers such as `protobuf-net` and others, it would be great if an extension point be made such as adding attributes to members (one workaround might be to add custom serialisation methods to a partial class or could we add `[DataMember(Order = 1)]/[DataContract]` by default).

**Comment by andrewlock** [comment]
Hmmm, that's an interesting one. As I understand it, [these sort of structs are not supported by `protobuf-net`](https://github.com/protobuf-net/protobuf-net#notes-on-types), so that one is probably a moot point? 

> The code assumes that types will be mutable around the elected members. Accordingly, custom structs are not supported, since they should be immutable.

With regard to other attributes, it would certainly be possible to add extra options, though as I don't use them, I'm a little hesitant to implement it myself. Happy to look at PRs of course 🙂

**Comment by andrewlock** [comment]
I think this is (finally) fully covered by the work in #117 which will be released soon!
